# Shell variables
# Generated by 'wal'
wallpaper='/home/zack/Pictures/wallpaper/headphones-paint-color-splash.jpg'

# Special
background='#110f1e'
foreground='#78ddea'
cursor='#78ddea'

# Colors
color0='#110f1e'
color1='#C14039'
color2='#076D8E'
color3='#5A6592'
color4='#0794B1'
color5='#5BA5B8'
color6='#03B1CC'
color7='#78ddea'
color8='#549aa3'
color9='#C14039'
color10='#076D8E'
color11='#5A6592'
color12='#0794B1'
color13='#5BA5B8'
color14='#03B1CC'
color15='#78ddea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
