--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zack/Pictures/wallpaper/headphones-paint-color-splash.jpg"

-- Special
background="#110f1e"
foreground="#78ddea"
cursor="#78ddea"

-- Colors
color0="#110f1e"
color1="#C14039"
color2="#076D8E"
color3="#5A6592"
color4="#0794B1"
color5="#5BA5B8"
color6="#03B1CC"
color7="#78ddea"
color8="#549aa3"
color9="#C14039"
color10="#076D8E"
color11="#5A6592"
color12="#0794B1"
color13="#5BA5B8"
color14="#03B1CC"
color15="#78ddea"
