import { Button, VerticalBox, ComboBox, HorizontalBox, ScrollView } from "std-widgets.slint";

export struct ColorType {
    name: string,
    rgb: string,
    hex: string,
    hsl: string,
    color: color,
    }

export struct PaletteType {
    name: string,
    colors: [ColorType],
    }

export global Copy {
    pure callback copy-on-click(string);
}

component ColorDisplay inherits Rectangle {
    width: 30px;
    height: root.width;
    border-radius: root.width / 2;
    padding: 5px;
}

component ColorText inherits VerticalBox {
    padding: 0px;
    in property <string> text;
    in property <int> font-weight: 450;
    in-out property <color> color-text;
    alignment: center;
    touch := TouchArea {
        Text {
            text: text;
            color: touch.has-hover ? color-text : Theme.foreground;
            font-weight: font-weight;
        }

        clicked => {
            Copy.copy-on-click(text);
        }
    }
}

component ColorLine inherits HorizontalBox {
    padding: 0px;
    in property <ColorType> Color;

    ColorDisplay {
        background: Color.color;
    }

    VerticalBox {
        alignment: center;
        padding: 0px;
        HorizontalBox {
            alignment: space-between;
            padding: 0px;
            ColorText {
                text: Color.name;
                font-weight: 600;
                color-text: Color.color;
            }

            ColorText {
                text: Color.rgb;
                color-text: Color.color;
            }

            ColorText {
                text: Color.hex;
                color-text: Color.color;
            }

            ColorText {
                text: Color.hsl;
                color-text: Color.color;
            }
        }
    }
}

component ColorPalette inherits VerticalBox {
    in-out property <string> name;
    in-out property <PaletteType> color-palette;
    width: 100%;
    spacing: 5px;

    for line in color-palette.colors: color-lines := ColorLine {
        Color: line;
    }
}

export global Theme {
    in-out property <color> background: rgb(0,0,0);
    in-out property <color> foreground: rgb(255,255,255);
    in-out property <string> font-family: "CaskaydiaCove NF";
    in-out property <length> font-size: 14px;
    in-out property <length> color-size: 28px;
}

export component AppWindow inherits Window {
    title: "Colour Palette";
    background: Theme.background;

    default-font-family: Theme.font-family;
    default-font-size: Theme.font-size;

    in-out property <PaletteType> palette;
    in-out property <[string]> available-palette;
    callback select-palette <=> palatte-selector.selected;
    callback refesh-palettes <=> refresh-button.clicked;

    VerticalBox {
        padding: 15px;
        spacing: 0px;
        alignment: center;
        HorizontalBox {
            alignment: center;
            palatte-selector := ComboBox {

                width: self.preferred-width;
                height: self.preferred-height;
                model: root.available-palette;
                current-value: root.palette.name;
            }
        }

        colour-palette := ColorPalette {
            color-palette: root.palette;
        }

        HorizontalBox {
            alignment: center;
            refresh-button := Button {
                text: "Refresh";
            }
        }
    }
}
